name: Observed

on:
  pull_request:

permissions:
  contents: read

jobs:
  observe:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: esau-morais/observed@d23c0538f1cabcb26d8ff95e6e7aca5bd3dbf6ed # feat/api-operations, unreleased
        env:
          OBSERVED_FROM_SOURCE: true
          STATIONS_TOKEN: ${{ secrets.STATIONS_TOKEN }}
        with:
          project: .
          base: ${{ github.event.pull_request.base.sha }}
          github-app-client-id: ${{ vars.OBSERVED_APP_CLIENT_ID }}
          github-app-private-key: ${{ secrets.OBSERVED_APP_PRIVATE_KEY }}
          slack-bot-token: ${{ secrets.OBSERVED_SLACK_BOT_TOKEN }}
          slack-channel: ${{ vars.OBSERVED_SLACK_CHANNEL }}
